In [6]:
import gym
import gym_molecule
import numpy as np

env = gym.make("molecule-v0")
env.init()
ob_space = env.observation_space
print(ob_space["node"].shape)
print(ob_space["adj"])
ob_node = ob_space["node"]
ob_nodes = np.array([ob_node for _ in range(3)])
print(ob_nodes)
ac = env.action_space.sample()
print(ac)

(1, 47, 9)
[13 37  2  0]


In [26]:
import argparse
parser = argparse.ArgumentParser(description='Process some integers.',formatter_class=argparse.ArgumentDefaultsHelpFormatter)
parser.add_argument('--sum',type=int,\
                   default=1,help = 'sum the integers (default: find the max)')
args = parser.parse_args([])
print(args.sum)

1


In [4]:
import tensorflow as tf

# Build a graph.
a = tf.Variable([2,3,0,-1,-4])
b = tf.cast(a,dtype = tf.bool)
c = tf.cast(b,dtype = tf.float32)
with tf.Session() as sess:
    sess.run(tf.initialize_all_variables())
    print(sess.run(c))

[1. 1. 0. 1. 1.]


In [11]:
import numpy as np
F = np.zeros((3,2))
print(F)
F[1,:]=[1,2]
print(F)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0. 0.]
 [1. 2.]
 [0. 0.]]
